name: Keep Render Server Alive

on:
  schedule:
    # Runs every 14 minutes
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Server
      run: |
        echo "Pinging server at $(date)"
        response=$(curl -s -o /dev/null -w "%{http_code}" https://aqi-prediction-future.onrender.com/api/health/)
        echo "Response code: $response"
        if [ $response -eq 200 ]; then
          echo "✅ Server is alive!"
        else
          echo "❌ Server ping failed with code: $response"
        fi
